env:
addons:
  apt:
    sources:
    - mono
    packages:
    - mono-runtime
    - libmono-cil-dev
    - build-essential
    - devscripts
    - debhelper
    - intltool
  ssh_known_hosts: d4.silvenga.net
dist: trusty
language: csharp
script:
- bash build.sh --target Build-Deb
after_success:
  - openssl aes-256-cbc -K $encrypted_2b0540bf1619_key -iv $encrypted_2b0540bf1619_iv -in tools/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - scp *.deb d4.silvenga.net:/opt/aptly/incoming/btsync/
  - ssh d4.silvenga.net "bash /opt/aptly/incoming/import.sh btsync; bash /opt/aptly/s3-publish.sh;"